package org.cohorte.utilities.installer;

public interface IConstants {
	String INSTALL_PATH = "INSTALL_PATH"; 
	String INSTALLER__IS_ALREADY_INSTALLED = "INSTALLER__IS_ALREADY_INSTALLED";
	String INSTALLER__ALREADY_INSTALLED_VERSION = "INSTALLER__ALREADY_INSTALLED_VERSION";
	String INSTALLER__NEW_VERSION = "INSTALLER__NEW_VERSION";
	String INSTALLER__DO_ACTION = "INSTALLER__DO_ACTION";
}
